#!/bin/bash
DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
export LD_PRELOAD=/usr/lib/${DEB_HOST_GNU_TYPE}/libdri2to3.so
export LD_LIBRARY_PATH=/usr/lib/${DEB_HOST_GNU_TYPE}/libmali-x11:/usr/lib/${DEB_HOST_GNU_TYPE}/gl4es
exec "$@"
